In [1]:
import pandas as pd 

tabela = pd.read_csv("07-dados-abertos-precos-glp.csv", sep=";", encoding="utf-8-sig")
display(tabela)

,Regiao - Sigla,Estado - Sigla,Municipio,Revenda,CNPJ da Revenda,Nome da Rua,Numero Rua,Complemento,Bairro,Cep,Produto,Data da Coleta,Valor de Venda,Valor de Compra,Unidade de Medida,Bandeira
0,SE,MG,MONTES CLAROS,SUPERGASBRAS ENERGIA LTDA,19.791.896/0070-24,AVENIDA DEP. PLINIO RIBEIRO,3220,NaN,JARDIM PALMEIRAS,39402-194,GLP,01/07/2026,"120,00",NaN,R$ / 13 kg,SUPERGASBRAS ENERGIA
1,NE,MA,SAO LUIS,C. G. DE SOUSA LTDA,69.425.734/0002-08,AVENIDA GUAJAJARA,205,NaN,SAO CRISTOVAO,65055-285,GLP,01/07/2026,"130,00",NaN,R$ / 13 kg,LIQUIGÁS
2,NE,PE,RECIFE,A.B. SILVA & CIA LTDA,10.973.568/0001-42,AVENIDA BEBERIBE,1021,LOJA 0000,PONTO DE PARADA,52041-375,GLP,01/07/2026,"99,99",NaN,R$ / 13 kg,BRANCA
3,NE,PE,RECIFE,SIVINI PETROLEO LTDA,02.998.548/0001-06,AVENIDA BEBERIBE SANTA CRUZ FUTEBOL CLUBE,3433,NaN,PORTO DA MADEIRA,52130-547,GLP,01/07/2026,"105,00",NaN,R$ / 13 kg,BAHIANA
4,NE,PI,TERESINA,POSTO HIDROLANDIA LTDA,03.069.763/0001-87,AVENIDA PREFEITO WALL FERRAZ,8570,SUL,LOURIVAL PARENTE,64022-145,GLP,01/07/2026,"110,00",NaN,R$ / 13 kg,BRANCA
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13770,SE,RJ,RIO BONITO,DISTRIBUIDORA DE GAS FERREIRA COSTA LTDA,43.826.071/0001-50,AV PRESIDENTE ARTHUR BERNARDES,122,NaN,CENTRO,28800-000,GLP,31/07/2026,"90,00",NaN,R$ / 13 kg,BRANCA
13771,SE,RJ,RIO BONITO,RB COMERCIO E TRANSPORTE DE GAS LTDA,48.928.829/0001-85,RUA ALBERTO OLIVEIRA VILA CRUZEIRO,32,QUADRA02 AREA 01,PRACA CRUZEIRO,28800-000,GLP,31/07/2026,"90,00",NaN,R$ / 13 kg,BRANCA
13772,SE,SP,BIRIGUI,NEW GAS BIRIGUI LTDA.,47.642.916/0001-09,AVENIDA EUCLIDES MIRAGAIA,2708,NaN,JARDIM JUSSARA MARIA,16204-000,GLP,31/07/2026,"110,00",NaN,R$ / 13 kg,BRANCA
13773,SE,SP,BIRIGUI,BIRIGAS COMERCIO VAREJISTA DE GAS LTDA,34.742.663/0002-84,AVENIDA EUCLIDES MIRAGAIA,1677,NaN,VILA PONTES,16200-130,GLP,31/07/2026,"92,00",NaN,R$ / 13 kg,SUPERGASBRAS ENERGIA
13774,CO,MT,ALTA FLORESTA,MB BRASIL COMERCIO DE GAS LTDA,53.960.348/0001-97,AVENIDA PERIMETRAL DEPUTADO FEDERAL ROGERIO LU...,2697,NaN,SETOR AP - D4,78580-000,GLP,31/07/2026,"145,00",NaN,R$ / 13 kg,COPA ENERGIA

In [2]:
df = tabela.dropna(axis=1)
display(df)
display(df.info())

,Regiao - Sigla,Estado - Sigla,Municipio,Revenda,CNPJ da Revenda,Nome da Rua,Numero Rua,Bairro,Cep,Produto,Data da Coleta,Valor de Venda,Unidade de Medida,Bandeira
0,SE,MG,MONTES CLAROS,SUPERGASBRAS ENERGIA LTDA,19.791.896/0070-24,AVENIDA DEP. PLINIO RIBEIRO,3220,JARDIM PALMEIRAS,39402-194,GLP,01/07/2026,"120,00",R$ / 13 kg,SUPERGASBRAS ENERGIA
1,NE,MA,SAO LUIS,C. G. DE SOUSA LTDA,69.425.734/0002-08,AVENIDA GUAJAJARA,205,SAO CRISTOVAO,65055-285,GLP,01/07/2026,"130,00",R$ / 13 kg,LIQUIGÁS
2,NE,PE,RECIFE,A.B. SILVA & CIA LTDA,10.973.568/0001-42,AVENIDA BEBERIBE,1021,PONTO DE PARADA,52041-375,GLP,01/07/2026,"99,99",R$ / 13 kg,BRANCA
3,NE,PE,RECIFE,SIVINI PETROLEO LTDA,02.998.548/0001-06,AVENIDA BEBERIBE SANTA CRUZ FUTEBOL CLUBE,3433,PORTO DA MADEIRA,52130-547,GLP,01/07/2026,"105,00",R$ / 13 kg,BAHIANA
4,NE,PI,TERESINA,POSTO HIDROLANDIA LTDA,03.069.763/0001-87,AVENIDA PREFEITO WALL FERRAZ,8570,LOURIVAL PARENTE,64022-145,GLP,01/07/2026,"110,00",R$ / 13 kg,BRANCA
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13770,SE,RJ,RIO BONITO,DISTRIBUIDORA DE GAS FERREIRA COSTA LTDA,43.826.071/0001-50,AV PRESIDENTE ARTHUR BERNARDES,122,CENTRO,28800-000,GLP,31/07/2026,"90,00",R$ / 13 kg,BRANCA
13771,SE,RJ,RIO BONITO,RB COMERCIO E TRANSPORTE DE GAS LTDA,48.928.829/0001-85,RUA ALBERTO OLIVEIRA VILA CRUZEIRO,32,PRACA CRUZEIRO,28800-000,GLP,31/07/2026,"90,00",R$ / 13 kg,BRANCA
13772,SE,SP,BIRIGUI,NEW GAS BIRIGUI LTDA.,47.642.916/0001-09,AVENIDA EUCLIDES MIRAGAIA,2708,JARDIM JUSSARA MARIA,16204-000,GLP,31/07/2026,"110,00",R$ / 13 kg,BRANCA
13773,SE,SP,BIRIGUI,BIRIGAS COMERCIO VAREJISTA DE GAS LTDA,34.742.663/0002-84,AVENIDA EUCLIDES MIRAGAIA,1677,VILA PONTES,16200-130,GLP,31/07/2026,"92,00",R$ / 13 kg,SUPERGASBRAS ENERGIA
13774,CO,MT,ALTA FLORESTA,MB BRASIL COMERCIO DE GAS LTDA,53.960.348/0001-97,AVENIDA PERIMETRAL DEPUTADO FEDERAL ROGERIO LU...,2697,SETOR AP - D4,78580-000,GLP,31/07/2026,"145,00",R$ / 13 kg,COPA ENERGIA

<class 'pandas.DataFrame'>
RangeIndex: 13775 entries, 0 to 13774
Data columns (total 14 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Regiao - Sigla     13775 non-null  str
 1   Estado - Sigla     13775 non-null  str
 2   Municipio          13775 non-null  str
 3   Revenda            13775 non-null  str
 4   CNPJ da Revenda    13775 non-null  str
 5   Nome da Rua        13775 non-null  str
 6   Numero Rua         13775 non-null  str
 7   Bairro             13775 non-null  str
 8   Cep                13775 non-null  str
 9   Produto            13775 non-null  str
 10  Data da Coleta     13775 non-null  str
 11  Valor de Venda     13775 non-null  str
 12  Unidade de Medida  13775 non-null  str
 13  Bandeira           13775 non-null  str
dtypes: str(14)
memory usage: 3.4 MB

None

In [3]:
df["Valor de Venda"] = df["Valor de Venda"].str.replace(",",".").astype(float)
display(df)

,Regiao - Sigla,Estado - Sigla,Municipio,Revenda,CNPJ da Revenda,Nome da Rua,Numero Rua,Bairro,Cep,Produto,Data da Coleta,Valor de Venda,Unidade de Medida,Bandeira
0,SE,MG,MONTES CLAROS,SUPERGASBRAS ENERGIA LTDA,19.791.896/0070-24,AVENIDA DEP. PLINIO RIBEIRO,3220,JARDIM PALMEIRAS,39402-194,GLP,01/07/2026,120.00,R$ / 13 kg,SUPERGASBRAS ENERGIA
1,NE,MA,SAO LUIS,C. G. DE SOUSA LTDA,69.425.734/0002-08,AVENIDA GUAJAJARA,205,SAO CRISTOVAO,65055-285,GLP,01/07/2026,130.00,R$ / 13 kg,LIQUIGÁS
2,NE,PE,RECIFE,A.B. SILVA & CIA LTDA,10.973.568/0001-42,AVENIDA BEBERIBE,1021,PONTO DE PARADA,52041-375,GLP,01/07/2026,99.99,R$ / 13 kg,BRANCA
3,NE,PE,RECIFE,SIVINI PETROLEO LTDA,02.998.548/0001-06,AVENIDA BEBERIBE SANTA CRUZ FUTEBOL CLUBE,3433,PORTO DA MADEIRA,52130-547,GLP,01/07/2026,105.00,R$ / 13 kg,BAHIANA
4,NE,PI,TERESINA,POSTO HIDROLANDIA LTDA,03.069.763/0001-87,AVENIDA PREFEITO WALL FERRAZ,8570,LOURIVAL PARENTE,64022-145,GLP,01/07/2026,110.00,R$ / 13 kg,BRANCA
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13770,SE,RJ,RIO BONITO,DISTRIBUIDORA DE GAS FERREIRA COSTA LTDA,43.826.071/0001-50,AV PRESIDENTE ARTHUR BERNARDES,122,CENTRO,28800-000,GLP,31/07/2026,90.00,R$ / 13 kg,BRANCA
13771,SE,RJ,RIO BONITO,RB COMERCIO E TRANSPORTE DE GAS LTDA,48.928.829/0001-85,RUA ALBERTO OLIVEIRA VILA CRUZEIRO,32,PRACA CRUZEIRO,28800-000,GLP,31/07/2026,90.00,R$ / 13 kg,BRANCA
13772,SE,SP,BIRIGUI,NEW GAS BIRIGUI LTDA.,47.642.916/0001-09,AVENIDA EUCLIDES MIRAGAIA,2708,JARDIM JUSSARA MARIA,16204-000,GLP,31/07/2026,110.00,R$ / 13 kg,BRANCA
13773,SE,SP,BIRIGUI,BIRIGAS COMERCIO VAREJISTA DE GAS LTDA,34.742.663/0002-84,AVENIDA EUCLIDES MIRAGAIA,1677,VILA PONTES,16200-130,GLP,31/07/2026,92.00,R$ / 13 kg,SUPERGASBRAS ENERGIA
13774,CO,MT,ALTA FLORESTA,MB BRASIL COMERCIO DE GAS LTDA,53.960.348/0001-97,AVENIDA PERIMETRAL DEPUTADO FEDERAL ROGERIO LU...,2697,SETOR AP - D4,78580-000,GLP,31/07/2026,145.00,R$ / 13 kg,COPA ENERGIA

In [4]:
vendas_regiao = df[["Regiao - Sigla", "Valor de Venda"]].groupby("Regiao - Sigla").sum()
display(vendas_regiao)

                Valor de Venda
Regiao - Sigla
CO                   163686.18
N                    157772.14
NE                   311075.08
S                    291755.86
SE                   662976.14

In [5]:
vendas_estado = df[["Estado - Sigla", "Valor de Venda"]].groupby("Estado - Sigla").sum()
display(vendas_estado)

                Valor de Venda
Estado - Sigla
AC                     9244.00
AL                    20584.84
AM                    40211.00
AP                     7221.00
BA                    82228.47
CE                    29893.74
DF                    15023.04
ES                    33748.32
GO                    70565.02
MA                    41222.61
MG                   194671.81
MS                    29979.30
MT                    48118.82
PA                    46011.62
PB                    24935.96
PE                    56791.88
PI                    22445.73
PR                   117202.99
RJ                    86408.81
RN                    18545.75
RO                    26228.52
RR                    11990.00
RS                   126157.51
SC                    48395.36
SE                    14426.10
SP                   348147.20
TO                    16866.00

In [6]:
vendas_municipio = df[["Municipio", "Valor de Venda"]].groupby("Municipio").sum()
display(vendas_municipio)

                        Valor de Venda
Municipio
ABAETETUBA                     2812.00
ACAILANDIA                      250.00
ADAMANTINA                     2905.12
AGUAS LINDAS DE GOIAS          5571.84
ALAGOINHAS                     4094.86
...                                ...
VITORIA DE SANTO ANTAO         3202.96
VOLTA REDONDA                  3414.95
VOTORANTIM                     2465.91
VOTUPORANGA                    4452.96
XANXERE                        2319.20

[411 rows x 1 columns]

In [7]:
import plotly.express as px

grafico_regioes = px.bar(x=df["Regiao - Sigla"], y=df["Valor de Venda"], title="Vendas por regiao")
grafico_regioes.update_yaxes(title="Valor da venda") 
grafico_regioes.update_xaxes(title="Regiao")
grafico_regioes.update_traces(marker_color="#E53935")
grafico_regioes.show()

In [8]:

grafico_estados = px.bar(x=df["Estado - Sigla"], y=df["Valor de Venda"], title="Vendas por estado")
grafico_estados.update_yaxes(title="Valor de venda")
grafico_estados.update_xaxes(title="Estado")
grafico_estados.update_traces(marker_color="#636EFA", opacity=1)
grafico_estados.show()